name: CI

on:
  push:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    environment: test
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: 'yarn'

      - name: ðŸ”‘ Create .env file
        uses: SpicyPizza/create-envfile@v1.3
        with:
          envkey_DATABASE_URL: ${{ secrets.DATABASE_URL }}
          envkey_NEXT_PUBLIC_SUPABASE_URL: ${{ secrets.NEXT_PUBLIC_SUPABASE_URL }}
          envkey_NEXT_PUBLIC_SUPABASE_ANON_KEY: ${{ secrets.NEXT_PUBLIC_SUPABASE_ANON_KEY }}
          envkey_SERVICE_ROLE_KEY: ${{ secrets.SERVICE_ROLE_KEY }}
          envkey_IMAGE_HOST_DOMAIN: ${{ secrets.IMAGE_HOST_DOMAIN }}
          envkey_PHOTO_BUCKET: ${{ secrets.PHOTO_BUCKET }}
          envkey_NEXT_PUBLIC_APP_NAME: ${{ secrets.NEXT_PUBLIC_APP_NAME }}
          envkey_NEXT_PUBLIC_API_URL: ${{ secrets.NEXT_PUBLIC_API_URL }}
          envkey_AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          envkey_AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          envkey_BUCKET_REGION: ${{ secrets.BUCKET_REGION }}
          directory: ./
          file_name: .env
          fail_on_empty: true

      - name: echo secrets
        run: |
          echo ${{ secrets.TEST_SECRET }} |
          echo ${{ secrets.DATABASE_URL}}

      - name: Show files
        run: |
          ls -la

      - name: ðŸ—ï¸ Install dependencies
        id: yarn-install
        run: yarn install --frozen-lockfile
      - uses: supabase/setup-cli@v1
        with:
          version: 1.0.0

      - name: Start Supabase local development setup
        run: supabase start

      - name: Verify generated types are up-to-date
        run: |
          supabase gen types typescript --local > types.ts
          if [ "$(git diff --ignore-space-at-eol types.ts | wc -l)" -gt "0" ]; then
            echo "Detected uncommitted changes after build. See status below:"
            git diff
            exit 1
          fi

      - name: Generate Prisma Client
        run: yarn prisma generate

      - name: Push Types to Supabase
        run: npx prisma db push

      - name: Seed db and apply functions
        run: npx prisma db seed

      - name: add dotenv
        run: yarn global add dotenv-cli

      - name: ðŸ§ª Unit tests
        run: yarn dotenv -e .env jest

      # - name: Download the build folders
      #   uses: actions/download-artifact@v2
      #   with:
      #     name: build
      #     path: build
      - name: Cache NPM and Cypress ðŸ“¦
        uses: actions/cache@v2
        with:
          path: |
            ~/.cache/Cypress
            node_modules
          key: my-cache-${{ runner.os }}-${{ hashFiles('yarn-lock.json') }}
      - name: Install Cypress ðŸ“¥
        run:
          yarn add
          https://cdn.cypress.io/beta/npm/10.0.0/linux-x64/10.0-release-04e5d70d48a1337b702f53ac9677350167eb7ae6/cypress.tgz
      - name: Cypress run
        uses: cypress-io/github-action@v4
      # - name: ðŸ›© E2E tests
      #   run: yarn e2e:headless
      # SUPABASE_ACCESS_TOKEN: ${{ secrets.SUPABASE_ACCESS_TOKEN }}
      # SUPABASE_DB_PASSWORD: ${{ secrets.STAGING_DB_PASSWORD }}
      # STAGING_PROJECT_ID: abcdefghijklmnopqrst
